version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - APP_DB_HOST=localhost
      - APP_DB_PORT=3306
      - APP_DB_NAME=nestjs
      - APP_DB_USER=root
      - APP_DB_PASS=
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    command: >
      sh -c "npx nx run api:migrate && npm run build && npm run start:prod"

volumes:
  db_data:
